{{- if .Values.istio.enabled }}
{{- range $serviceName, $config := .Values.services }}
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ $config.name }}-destination-rule
  namespace: {{ $.Values.global.namespace }}
spec:
  host: {{ $config.serviceName }}.{{ $.Values.global.namespace }}.svc.cluster.local
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 10
      http:
        http1MaxPendingRequests: 10
        maxRequestsPerConnection: 2
    loadBalancer:
      simple: LEAST_CONN
    outlierDetection:
      consecutiveErrors: 3
      interval: 30s
      baseEjectionTime: 30s
{{- end }}
{{- end }}
