{{- range $serviceName, $config := .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $config.serviceName }} 
  namespace: {{ $.Values.global.namespace }}
spec:
  selector:
    app: {{ $config.name }}
  ports:
    - name: http
      port: {{ $config.port }}
      targetPort: {{ $config.port }}
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: {{ $config.serviceName }}-preview 
  namespace: {{ $.Values.global.namespace }}
spec:
  selector:
    app: {{ $config.name }}
  ports:
    - name: http
      port: {{ $config.port }}
      targetPort: {{ $config.port }}
  type: ClusterIP
{{- end }}
