apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: kubox-secrets-provider
  namespace: default
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "kubox/backend/production"
        objectType: "secretsmanager"
        jmesPath:
          - path: "JWT_SECRET_KEY"
            objectAlias: "JWT_SECRET_KEY"
          - path: "DB_PASSWORD"
            objectAlias: "DB_PASSWORD"
          - path: "MYSQL_ROOT_PASSWORD"
            objectAlias: "MYSQL_ROOT_PASSWORD"
          - path: "MYSQL_PASSWORD"
            objectAlias: "MYSQL_PASSWORD"
          - path: "BOOTPAY_APPLICATION_ID"
            objectAlias: "BOOTPAY_APPLICATION_ID"
          - path: "BOOTPAY_PRIVATE_KEY"
            objectAlias: "BOOTPAY_PRIVATE_KEY"
  secretObjects:
  - secretName: kubox-backend-secrets
    type: Opaque
    data:
    - objectName: "JWT_SECRET_KEY"
      key: "JWT_SECRET_KEY"
    - objectName: "DB_PASSWORD"
      key: "DB_PASSWORD"
    - objectName: "MYSQL_ROOT_PASSWORD"
      key: "MYSQL_ROOT_PASSWORD"
    - objectName: "MYSQL_PASSWORD"
      key: "MYSQL_PASSWORD"
    - objectName: "BOOTPAY_APPLICATION_ID"
      key: "BOOTPAY_APPLICATION_ID"
    - objectName: "BOOTPAY_PRIVATE_KEY"
      key: "BOOTPAY_PRIVATE_KEY"
